<?php
// $Id$

/**
 * Provides some minor enhancements to the checkout page.
 *
 * Currently makes the following changes:
 * - Removes the cancel button from the checkout form.
 * - Adds a throbber and disables the 'Submit Order' button to prevent
 *   multiple clicks.
 */

/**
 * Implementation of hook_menu().
 */
function uc_checkout_enhance_menu($may_cache) {
  $items[] = array(
    'path' => 'admin/store/settings/checkout-enhance',
    'title' => t('Checkout enhancements'),
    'callback' => 'drupal_get_form',
    'callback arguments' => array('uc_checkout_enhance_admin'),
    'access' => user_access('administer store'),
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function uc_checkout_enhance_form_alter($form_id, &$form) {
  if ($form_id == 'uc_cart_checkout_form') {
    if (variable_get('uc_ce_no_cancel', TRUE)) {
      unset($form['cancel']);
    }
  }
  elseif ($form_id == 'uc_cart_checkout_review_form') {
    // Patched by quicksketch for IE compatibility and better handling!
    if (variable_get('uc_ce_submit_disable', TRUE)) {
      drupal_add_js("
$('document').ready(function() {
  $('form#uc-cart-checkout-review-form input#edit-submit').click(function() {
    $(this).clone().insertAfter(this).attr('disabled', true).after('<span id=\"submit-throbber\" style=\"background: url(' + Drupal.settings['base_path'] + 'misc/throbber.gif) no-repeat 100% -20px;\">&nbsp;&nbsp;&nbsp;&nbsp;</span>').end().hide();
  });
});", 'inline');
    }
  }
}

// Displays the admin form to toggle the various enhancements.
function uc_checkout_enhance_admin() {
  $form['uc_ce_no_cancel'] = array(
    '#type' => 'checkbox',
    '#title' => t('Remove the cancel button from the checkout form.'),
    '#description' => t('Affects the form at /cart/checkout.'),
    '#default_value' => variable_get('uc_ce_no_cancel', TRUE),
  );
  $form['uc_ce_submit_disable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add a throbber to the submit order button and disable multiple form submissions.'),
    '#description' => t('Affects the form at /cart/checkout/review.'),
    '#default_value' => variable_get('uc_ce_submit_disable', TRUE),
  );

  return system_settings_form($form);
}
