<?php
// пути для собственных переопределённых нодов с корзиной и ордером

define('MY_CART_NODE', 'node/6');
define('MY_CART_CHECKOUT_NODE', 'node/7');
define('MY_CART_REVIEW_NODE', 'node/8');
define('MY_CART_COMPLETE_NODE', 'node/9');

define('MY_CART_NODE_NUM', '6');
define('MY_CART_CHECKOUT_NODE_NUM', '7');
define('MY_CART_REVIEW_NODE_NUM', '8');
define('MY_CART_COMPLETE_NODE_NUM', '9');



define('MY_ORDER_HISTORY_NODE', 'node/10');
define('MY_ORDER_REVIEW_NODE', 'node/11');
define('MY_ORDER_EDIT_NODE', 'node/40');

define('MY_ORDER_HISTORY_NODE_NUM', '10');
define('MY_ORDER_REVIEW_NODE_NUM', '11');
define('MY_ORDER_EDIT_NODE_NUM', '40');


define('MY_USER_SETTINGS_NODE', 'node/22');
define('MY_ZP_COMMENTS_NODE', 'node/23');

define('MY_USER_SETTINGS_NODE_NUM', '22');
define('MY_ZP_COMMENTS_NODE_NUM', '23');


define('MY_PASSREMIND_NODE', 'node/4519');
define('MY_PASSREMIND_NODE_NUM', '4519');

define('MY_ISSUESLIST_NODE', 'node/4523');
define('MY_ISSUESLIST_NODE_NUM', '4523');

define('MY_ISSUES_SPRAVKA_LIST_NODE', 'node/13202');
define('MY_ISSUES_SPRAVKA_LIST_NODE_NUM', '13202');

define('MY_MCLIST_NODE', 'node/4528');
define('MY_MCLIST_NODE_NUM', '4528');

define('MY_SHOPSLIST_NODE', 'node/4530');
define('MY_SHOPSLIST_NODE_NUM', '4530');

define('MY_HOME_PAGE_NODE', 'node/1');
define('MY_HOME_PAGE_NODE_NUM', '1');


define('MY_ZP_BLOG_NODE', 'node/14');
define('MY_ZP_BLOG_NODE_NUM', '14');

define('MY_ZP_NEWS_NODE', 'node/15');
define('MY_ZP_NEWS_NODE_NUM', '15');

define('MY_ZP_ADDSHOP_NODE_NUM', '17');


define('MY_ZP_PAGENOTFOUND_NODE', 'node/76');
define('MY_ZP_PAGENOTFOUND_NODE_NUM', '76');

define('MY_ZP_ACCESSDENIED_NODE', 'node/78');
define('MY_ZP_ACCESSDENIED_NODE_NUM', '78');

?>